### ISSUE TITLE
Crispy copy number input file and CRISPR screen input file format question

### ISSUE THREAD

**Issue by laulabbumc** [EmanuelGoncalves/crispy#2]
Dear Dr. Gonçalves,

I really like your Crispy paper, and I am trying to use Cripsy gene copy number ratio  to correct our in-house CRISPR screen data.

I have downloaded CCLE copy number segment file :

>>more CCLE_segment_cn.csv
DepMap_ID,Chromosome,Start,End,Segment_Mean,Num_Probes,Status,Source
ACH-000001,1,0,6275858,1.7621356648395683,5148,+,Broad WGS
ACH-000001,1,6275859,7079442,2.4909654303888336,792,+,Broad WGS
ACH-000001,1,7079443,7502035,1.8494047510652951,417,+,Broad WGS
ACH-000001,1,7502035,14866457,1.7784014133107096,6664,+,Broad WGS
ACH-000001,1,14866458,15395313,2.450037786788354,514,+,Broad WGS
ACH-000001,1,15395314,16193821,1.896562611077248,669,+,Broad WGS
ACH-000001,1,16193822,16540624,0.6786586410933554,320,-,Broad WGS
ACH-000001,1,16540625,16714625,1.1495569977055504,112,+,Broad WGS
ACH-000001,1,16714625,16824125,0.21027000944192087,51,-,Broad WGS
ACH-000001,1,16824125,16952624,1.1637054997560865,96,+,Broad WGS
ACH-000001,1,16952625,30006371,0.6013967597557067,12311,-,Broad WGS
ACH-000001,1,30006372,30016464,1.2008082209857775e-08,8,-,Broad WGS
ACH-000001,1,30016465,31640468,0.611072304220861,1481,-,Broad WGS
ACH-000001,1,31640469,34408919,0.9093181156794582,2705,0,Broad WGS
ACH-000001,1,34408920,35181710,2.0345348600584243,739,+,Broad WGS
ACH-000001,1,35181711,44564369,0.8826583328748431,9133,-,Broad WGS
ACH-000001,1,44564370,45025720,1.1983281253956508,436,+,Broad WGS
ACH-000001,1,45025721,52779891,0.9128286640381652,7201,0,Broad WGS

… …

And we have CRIPSR screen file in format like:

An example format of read-count.txt
[sgRNA tag]  \t  [GENE]  \t [sample 1] \t [sample 2] ...
ATAGATGTCCTGTGGCCCCG-P53 [tab] TP53 [tab] 403 [tab] 362 ....
ACTCACTTCCTGTGGCCCCG-MDM2 [tab] MDM2 [tab] 45 [tab] 64 ....

When I run to run the examply.py from Crispy package:

>>python example.py
......
 FutureWarning: The sklearn.metrics.ranking module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.metrics. Anything that cannot be imported from sklearn.metrics is now part of the private API.
  warnings.warn(message, FutureWarning)
Traceback (most recent call last):
  File "example.py", line 8, in <module>
    rawcounts, copynumber = cy.Utils.get_example_data()
  File "/mnt/efs/home/stb3865/software/anaconda3/lib/python3.8/site-packages/crispy/Utils.py", line 195, in get_example_data
    raw_counts = pd.read_csv(
  File "/mnt/efs/home/stb3865/software/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/mnt/efs/home/stb3865/software/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/mnt/efs/home/stb3865/software/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/mnt/efs/home/stb3865/software/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/mnt/efs/home/stb3865/software/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File /mnt/efs/home/stb3865/software/anaconda3/lib/python3.8/site-packages/crispy/data//example_rawcounts.csv does not exist: '/mnt/efs/home/stb3865/software/anaconda3/lib/python3.8/site-packages/crispy/data//example_rawcounts.csv'

Because there is no example_rawcounts.csv In the package:

I do not know the input file formats for  Crispy copy number input file and CRISPR screen input file format.

Could you tell me the formats for Crispy copy number input file and CRISPR screen input file format so that I could run the examply.py program ?

Thanks,

**Comment by laulabbumc** [comment]
Basically I need 3 sample files: sample_count_file, sample_copy_number_file, and sample_library_file by which I can understand your input formats and I can run through your examply.py program.

**Comment by EmanuelGoncalves** [comment]
This was an incomplete merge, thanks for flagging. I've updated the example and included the missing files. 

Update your installation  `pip install -U cy` 

In the example, I've also added a few more details on the file requirements and you can consult the pandas dataframes for a running example.

**Comment by laulabbumc** [comment]
I updated your code, I guess the sample data use Yusa_v1.1.csv after I "GREP" some gRNA name, but I still get an issue with Crispy:
(base) stb3865@Insight-hpc1>>python example.py
Traceback (most recent call last):
  File "example.py", line 15, in <module>
    crispy = cy.Crispy( sgrna_fc="/mnt/efs/home/stb3865/software/anaconda3/lib/python3.8/site-packages/crispy/data/example_rawcounts.csv",  copy_number="/mnt/efs/home/stb3865/software/anaconda3/lib/python3.8/site-packages/crispy/data",  library="/mnt/efs/home/stb3865/software/anaconda3/lib/python3.8/site-packages/crispy/data/crispr_libs/Yusa_v1.1.csv")
  File "/mnt/efs/home/stb3865/software/anaconda3/lib/python3.8/site-packages/crispy/CopyNumberCorrection.py", line 47, in __init__
    self.library.index.name = "index"
AttributeError: 'builtin_function_or_method' object has no attribute 'name'

**Comment by laulabbumc** [comment]
This is how I call it:
   crispy = cy.Crispy( sgrna_fc="/mnt/efs/home/stb3865/software/anaconda3/lib/python3.8/site-packages/crispy/data/example_rawcounts.csv",  copy_number="/mnt/efs/home/stb3865/software/anaconda3/lib/python3.8/site-packages/crispy/data/example_copynumber.csv",  library="/mnt/efs/home/stb3865/software/anaconda3/lib/python3.8/site-packages/crispy/data/crispr_libs/Yusa_v1.1.csv")

When I run it, I get an error message:
>>python example.py
Traceback (most recent call last):
  File "example.py", line 15, in <module>
    crispy = cy.Crispy( sgrna_fc="/mnt/efs/home/stb3865/software/anaconda3/lib/python3.8/site-packages/crispy/data/example_rawcounts.csv",  copy_number="/mnt/efs/home/stb3865/software/anaconda3/lib/python3.8/site-packages/crispy/data/example_copynumber.csv",  library="/mnt/efs/home/stb3865/software/anaconda3/lib/python3.8/site-packages/crispy/data/crispr_libs/Yusa_v1.1.csv")
  File "/mnt/efs/home/stb3865/software/anaconda3/lib/python3.8/site-packages/crispy/CopyNumberCorrection.py", line 47, in __init__
    self.library.index.name = "index"
AttributeError: 'builtin_function_or_method' object has no attribute 'name'

**Comment by EmanuelGoncalves** [comment]
The input of Crispy are pandas `dataframes` for `copy_number` and library and pandas series for `sgrna_fc`

You have an example on how the data should be structured.

**Comment by laulabbumc** [comment]
Could you please provide a working sample for example_rawcounts.csv which is a pandas dataframe, not pandas series for sgrna_fc ? Thank you!

**Comment by laulabbumc** [comment]
Could you please tell me that pandas series for sgrna_fc  file is just the ratio between treatment and control or log2(the ratio between treatment and control) ? Thank you!

**Comment by EmanuelGoncalves** [comment]
You should have all that in the example in the initial page of the project github, have you tried to run it? Below for your convenience:

```
import crispy as cy
import matplotlib.pyplot as plt
from crispy.CRISPRData import ReadCounts, Library

"""
Import sample data
"""
rawcounts, copynumber = cy.Utils.get_example_data()

"""
Import CRISPR-Cas9 library

Important:
      Library has to have the following columns: "Chr", "Start", "End", "Approved_Symbol"
      Library and segments have to have consistent "Chr" formating: "Chr1" or "chr1" or "1"
      Gurantee that "Start" and "End" columns are int
"""
lib = Library.load_library("Yusa_v1.1.csv.gz")

lib = lib.rename(
    columns=dict(start="Start", end="End", chr="Chr", Gene="Approved_Symbol")
).dropna(subset=["Chr", "Start", "End"])

lib["Chr"] = "chr" + lib["Chr"]

lib["Start"] = lib["Start"].astype(int)
lib["End"] = lib["End"].astype(int)

"""
Calculate fold-change
"""
plasmids = ["ERS717283"]
rawcounts = ReadCounts(rawcounts).remove_low_counts(plasmids)
sgrna_fc = rawcounts.norm_rpm().foldchange(plasmids)

"""
Correct CRISPR-Cas9 sgRNA fold changes
"""
crispy = cy.Crispy(
    sgrna_fc=sgrna_fc.mean(1), copy_number=copynumber, library=lib.loc[sgrna_fc.index]
)

# Fold-changes and correction integrated funciton.
# Output is a modified/expanded BED formated data-frame with sgRNA and segments information
#   n_sgrna: represents the minimum number of sgRNAs required per segment to consider in the fit.
#            Recomended default values range between 4-10.
bed_df = crispy.correct(n_sgrna=10)
print(bed_df.head())

# Gaussian Process Regression is stored
crispy.gpr.plot(x_feature="ratio", y_feature="fold_change")
plt.show()
```

**Comment by laulabbumc** [comment]
It works! Thanks!
Now I got the gene copy number ratio corrected log2 fold change. 
Could you please tell me how I could convert the new gene copy number ratio corrected log2 fold change back to the gene copy number ratio corrected raw count so that I could run BAGEL2 which only takes raw counts as inputs ? Thanks!
